var GAME_LEVELS = [

  ["                                                       ",                          
   "            xxx   xxxxx   xxx   xxxx   xxxxx           ",                                
   "           x!!!x  !!x!!  x!!!x  x!!!x  !!x!!           ",            
   "           x        x    x!!!x  x!!!x    x             ",            
   "            xx      x    x!!!x  x!!!x    x             ",                      
   "             xx     x    xxxxx  xxxx     x             ",                       
   "               x    x    x!!!x  x!!x     x             ",          
   "           x!!!x    x    x v x  x   x    x             ",              
   "            xxx     x    x   x  x   x    x             ",       
   "                                                       ",
   "                                            o          ",
   "g          @                                           ",        
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                       "],                   
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                 x!!!!!x         ",
   "                                                                xx!!!xx         ",
   "                                   xxxxx                         x v x          ",
   "  @                                                                        xx   ",
   "  xx                                      o o                                x  ",
   "  x                    o                                                     x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x          x  x                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                            x",
   "                                                                               xx           x",
   "                                                                               xx           x",
   "                                                                              xxxxxxxx o    x",
   "                                                                              xxxxxxxx      x",
   "                    xxxxx                        o                            xxxxxxxx      x",
   "                    x!!!x                                                    xxxx=     o    x",
   "                    x v x                    o  xxx                          xxxx          =x",
   "                    x   x                        !=                          xxxx=          x",
   "                xxxxx   xxxxx           o   xxx                            xxxxxx      o   =x",
   "                x       o                    !=                                xx           x",
   "@               x                      xxx                                xxxxxxx         xxx",
   "xxx          xxxx       o               !=                                 o xxxx      o xxxx",
   "xxx          x=                                                  xxxxx       xxxx    xxxxxxxx",
   "xxxxxxxxxxxxxx!!xxxxxxx   xxxxx   xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxx   xxxxxxxxxxxx oo xxxxxxxx",
   "             xxxx             x   x                  x!!!!!x                      oo xxxxxxxx",
   "                              xxxxx                  xxxxxxx                      oo         ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             "], 
  ["                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                              o                 ",
   "                                                                                                                ",
   "                                                                    x                           o               ",
   "                                                          o  x  o  ^x                o   xxxx                  x",
   "                                                             x      x                         o                x",
   "                                                             x     ^x               xxxx                       x",
   "                                                            xx  o   x           o               o              x",
   "                                                             x     ^x                                          x",
   "                                                          o  x      x          xxxx          o                 x",
   "                                                             x  o  ^x      o                                   x",
   "                                         o                  xx      x                          o               x",
   "                                                             x      x     xxxx               o                 x",
   "                                        xxx                  x  o                                              x",
   "                                      o x!x o                x                                                 x",
   "                                        x!x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx o      !x",
   "                                        x!x           x!                                                      !x",
   "                                      xxx!xxx  xxx    x!                                                     =!x",
   "                                       x!v!x          x!    o                                          o      !x",
   "                                                      x!=                                                     !x",
   "                                                     xx!xxxxxxxxxxxx          o                        o      !x",
   "                                                      x!                xx                                   =!x",
   "                                                      x!                      xx          o            o      !x",
   "                                                      x!=                           xx                        !x",
   "                                                  xxxxx!                                  xx           o      !x",
   "                                                 ^xxxxx!                                        xx            !x",
   "                                                  xxxxx!                                                      !x",
   "                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      !x",
   "                                           ^xxxxxxxxxxx                                                        x",
   "                                            xxxxxxxxxxx                                                        x",
   "                                      xxxxxxxxxxxxxxxxx                                                        x",
   "                 o             o      xxxxxxxxxxxxxxxxx o                                                      x",
   "@                                  g  xxxxxxxxxxxxxxxxx                                                   g    x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                ",
   "                                                                                                                "],   
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!xx        x                                    o   o   o  x!x  ",
   "                                                x!!!x        x     o   o                                    xx!x  ",
   "                                               xx v xx       x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                             x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx           xxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            x                        ",
   "                                                               xxxx!!!!!xxxx             v                        ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xx  x   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                     ^x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                 xx  xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                     ^x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                             xx      xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                     ^x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxxx                             ",
   "                                xx   xx   xx          x                     x!!!!x                            ",
   "                              o  o    x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xx  xxx xxx     o o  x!!!!!!!!!!!!!!x                   v x                  ",
   "                             x xxx   x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "  @                          xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x              o xxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x                 x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
